import {StyleSheet} from 'react-native';

export const Styles = StyleSheet.create({
  flex: {
    height: '82%',
    borderRadius: 20,
  },
  container: {
    width: '100%',
    alignItems: 'center',
    top: -120,
  },
  product_container: {
    width: 300,
    height: 300,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 160,
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 7},
    shadowRadius: 10,
    elevation: 3,
  },
  product_image: {
    resizeMode: 'contain',
    width: 180,
    height: 180,
  },
  product_content: {
    width: '90%',
    padding: 20,
    alignItems: 'center',
    backgroundColor: '#fff',
    marginTop: 20,
    borderRadius: 20,
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 7},
    shadowRadius: 10,
    elevation: 3,
  },
  product_name_text: {
    fontSize: 24,
    color: '#021B79',
    fontWeight: 'bold',
  },
  product_detail_text: {
    fontSize: 18,
    marginTop: 10,
  },
  product_price_text: {
    fontSize: 28,
    marginTop: 20,
    fontWeight: 'bold',
    color: '#000',
  },
  paymentTitle_content: {
    width: '90%',
    alignItems: 'flex-start',
  },
  payment_title_text: {
    fontSize: 22,
    marginTop: 30,
    fontWeight: 'bold',
    textAlign: 'left',
  },
  btn_payment_content: {
    width: '100%',
    paddingLeft: 120,
    marginTop: 60,
  },
  btn_payment: {
    width: 240,
    height: 240,
    backgroundColor: '#fff',
    margin: 10,
    borderRadius: 20,
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 3},
    shadowRadius: 10,
    elevation: 3,
    marginLeft: '0%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cash_image: {
    width: 200,
    height: 200,
    resizeMode: 'contain',
  },
  flatListStyle: {
    margin: 10,
    marginTop: 20,
  },
  btn_cancel_container: {
    width: '100%',
    backgroundColor: 'red',
    borderBottomRightRadius: 20,
    borderBottomLeftRadius: 20,
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 7},
    shadowRadius: 10,
    elevation: 3,
    marginTop: 30,
  },
  btn_cancel_content: {
    borderBottomRightRadius: 20,
    borderBottomLeftRadius: 20,
    padding: 20,
  },
  cancel_text: {
    textAlign: 'center',
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 24,
  },
  w100: {
    width: '100%',
  },
  timer_container: {
    width: '100%',
    alignItems: 'center',
    marginTop: 70,
  },
  timer_content: {
    width: '22%',
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: '#fff',
    padding: 5,
    borderRadius: 20,
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 3},
    shadowRadius: 10,
    elevation: 3,
  },
  timer_text: {
    fontSize: 25,
    color: '#FF4B2B',
    fontWeight: 'bold',
  },
});
