import {StyleSheet} from 'react-native';

export const Styles = StyleSheet.create({
  body_container: {
    width: '100%',
    alignItems: 'center',
  },
  bg_container: {
    width: 950,
    height: 950,
    resizeMode: 'contain',
    alignItems: 'center',
  },
  container: {
    width: '70%',
    alignItems: 'center',
    marginTop: '5%',
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 20,
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 3},
    shadowRadius: 10,
    elevation: 3,
  },
  timer_content: {
    width: '30%',
    padding: 20,
    borderRadius: 20,
    borderWidth: 4,
    borderColor: '#ddd',
    alignItems: 'center',
    justifyContent: 'center',
  },
  timer_title_text: {
    color: '#000',
    fontSize: 18,
  },
  timer_text: {
    color: '#021B79',
    fontSize: 40,
    fontWeight: 'bold',
  },
  image_payment: {
    width: 150,
    height: 150,
    resizeMode: 'contain',
  },
  title_content: {
    width: '70%',
    alignItems: 'center',
  },
  title_text: {
    color: '#021B79',
    fontWeight: 'bold',
    fontSize: 22,
    textAlign: 'center',
  },
  product_price_container: {
    width: '40%',
    flexDirection: 'row',
    marginTop: '5%',
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 3},
    shadowRadius: 10,
    elevation: 3,
    padding: 10,
    backgroundColor: '#fff',
    borderRadius: 10,
  },
  price_text_content: {
    width: '40%',
    alignItems: 'center',
    left: -40,
    marginTop: 20,
    position: 'absolute',
  },
  prduct_image_content: {
    width: '90%',
    alignItems: 'center',
  },
  prduct_name_text: {
    color: '#000',
    marginTop: 10,
    fontSize: 16,
    textAlign: 'center',
  },
  unit_text_content: {
    width: '35%',
    alignItems: 'flex-end',
  },
  price_text: {
    marginTop: '20%',
    fontSize: 24,
    fontWeight: '700',
    color: '#fff',
    paddingLeft: 15,
    paddingRight: 15,
    borderRadius: 10,
    backgroundColor: '#0cdfa0',
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 3},
    shadowRadius: 10,
    elevation: 3,
  },
  initPrice_text: {
    fontSize: 24,
    fontWeight: '700',
    color: '#fff',
  },
  qrcode_container: {
    width: '50%',
    alignItems: 'center',
    marginTop: '3%',
  },
  product_image: {
    width: 70,
    height: 70,
    resizeMode: 'contain',
  },
  mobile_banking_container: {
    width: '70%',
    alignItems: 'center',
  },
  mobile_banking_image: {
    width: 500,
    height: 100,
    resizeMode: 'contain',
  },
  cradit_card_image: {
    width: 300,
    height: 100,
    resizeMode: 'contain',
  },
  qrcode_content: {
    width: 270,
    height: 270,
    backgroundColor: '#fff',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: '2%',
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 3},
    shadowRadius: 10,
    elevation: 3,
  },
  qrcode_image: {
    width: 250,
    height: 250,
    resizeMode: 'contain',
  },
  btn_cancel_container: {
    width: '50%',
    backgroundColor: 'red',
    borderRadius: 10,
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 7},
    shadowRadius: 10,
    elevation: 3,
    marginTop: '3%',
    marginBottom: '2%',
  },
  btn_cancel_content: {
    width: '100%',
    padding: 10,
    borderRadius: 10,
  },
  btn_cancel_text: {
    textAlign: 'center',
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 24,
  },
  error_container: {
    width: '100%',
    height: '80%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  error_image: {
    width: 400,
    height: 400,
    resizeMode: 'contain',
    marginTop: '40%',
  },
  vending_process_image: {
    width: 480,
    height: 470,
    resizeMode: 'contain',
    top: 80,
  },
  down_image: {
    width: 180,
    height: 180,
    resizeMode: 'contain',
    marginTop: 40,
  },
  vending_process_text: {
    color: '#021B79',
    fontWeight: 'bold',
    fontSize: 26,
    marginTop: 20,
  },
  pickup_container: {
    width: '50%',
    padding: 16,
    borderRadius: 10,
    borderColor: '#FF416C',
    backgroundColor: '#ED213A',
    borderWidth: 3,
    marginTop: 50,
    alignItems: 'center',
  },
  pickup_text: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 26,
    textAlign: 'center',
  },
  icon_pickup: {
    bottom: 13,
    marginRight: 5,
  },
});
