import {StyleSheet} from 'react-native';

export const Styles = StyleSheet.create({
  flex: {
    flex: 1,
    padding: 20,
  },
  title_cotainer: {
    width: '100%',
    flexDirection: 'row',
  },
  title_content: {
    width: '30%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 10,
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 7},
    shadowRadius: 10,
    elevation: 3,
    marginRight: '2%',
  },
  title_text: {
    fontSize: 36,
    fontWeight: 'bold',
  },
  setting_image: {
    width: 200,
    height: 200,
    resizeMode: 'contain',
  },
  kisok_setting_contaniner: {
    width: '75%',
    justifyContent: 'center',
  },
  kisok_setting_content: {
    width: '68%',
    backgroundColor: '#fff',
    padding: 40,
    borderRadius: 10,
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 7},
    shadowRadius: 10,
    elevation: 3,
    flexDirection: 'row',
  },
  topic_content: {
    width: '90%',
    flexDirection: 'row',
  },
  title_input_content: {
    width: '40%',
    marginTop: '5%',
    justifyContent: 'center',
    padding: 10,
  },
  title_input_text: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  kiosk_input: {
    marginTop: '5%',
    width: '60%',
    padding: 10,
    borderRadius: 10,
    shadowColor: 'black',
    shadowOpacity: 0.3,
    shadowOffset: {width: 2, height: 0},
    shadowRadius: 10,
    elevation: 3,
    color: '#021B79',
    fontSize: 22,
    fontWeight: 'bold',
  },
  btn_save_content: {
    width: '25%',
    backgroundColor: '#a8e063',
    padding: 20,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: 'black',
    shadowOpacity: 0.3,
    shadowOffset: {width: 2, height: 0},
    shadowRadius: 10,
    elevation: 3,
  },
  btn_save_text: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#fff',
  },
  btn_setting_container: {
    width: '100%',
    flexDirection: 'row',
    marginTop: '10%',
    marginBottom: '10%',
  },
  btn_settingDevice_container: {
    width: '70%',
    alignItems: 'flex-end',
  },
  btn_settingDevice_content: {
    width: '30%',
    padding: 20,
    backgroundColor: '#ddd',
    alignItems: 'center',
    borderRadius: 10,
    shadowColor: 'black',
    shadowOpacity: 0.3,
    shadowOffset: {width: 2, height: 0},
    shadowRadius: 10,
    elevation: 3,
  },
  btn_settingDevice_text: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  btn_settingDevice_container_footer: {
    width: '70%',
    alignItems: 'flex-end',
  },
  btn_exit_container: {
    width: '30%',
    alignItems: 'center',
  },
  btn_exit_content: {
    width: '90%',
    padding: 20,
    backgroundColor: '#ED213A',
    alignItems: 'center',
    borderRadius: 10,
    shadowColor: 'black',
    shadowOpacity: 0.3,
    shadowOffset: {width: 2, height: 0},
    shadowRadius: 10,
    elevation: 3,
  },
  btn_exit_text: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
  },
});
