import {StyleSheet} from 'react-native';

export const Styles = StyleSheet.create({
  flex: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  container: {
    width: '60%',
    alignItems: 'center',
    borderRadius: 20,
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowOffset: {width: 0, height: 5},
    shadowRadius: 10,
    elevation: 3,
    padding: 20,
  },
  close_container: {
    width: '100%',
    alignItems: 'flex-end',
  },
  title_text: {
    fontSize: 42,
    fontWeight: 'bold',
    color: '#fff',
  },
  inputBox_container: {
    width: '100%',
    flexDirection: 'row',
  },
  inputBox: {
    width: '85%',
    height: 83,
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
    backgroundColor: '#fff',
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowOffset: {width: 0, height: 5},
    shadowRadius: 10,
    elevation: 3,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  btn_clear: {
    width: '15%',
    height: 83,
    padding: 20,
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
    backgroundColor: '#f7b733',
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowOffset: {width: 0, height: 5},
    shadowRadius: 10,
    elevation: 3,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  password_text: {
    fontSize: 42,
    fontWeight: 'bold',
    color: '#0F2027',
  },
  numpad_container: {
    marginTop: 20,
  },
  btn_numpad: {
    width: '31%',
    margin: '1%',
    height: 140,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowOffset: {width: 0, height: 5},
    shadowRadius: 10,
    elevation: 3,
    marginRight: '2%',
  },
  zero_container: {
    width: '100%',
    alignItems: 'center',
  },
  btn_numpad_text: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#0F2027',
  },
  btn_clear_text: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#fff',
  },
  btn_enter_content: {
    width: '100%',
    height: 80,
    backgroundColor: '#2c3e50',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowOffset: {width: 0, height: 5},
    shadowRadius: 10,
    elevation: 3,
    marginTop: 20,
  },
  btn_enter_text: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#fff',
  },
  w100: {width: '100%'},
});
